apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.4
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Install wget
          microdnf update && microdnf install -y wget && microdnf clean all
          
          # Download the SQL file
          wget -O dataSetGoogle "https://drive.google.com/uc?export=download&id=1SDsrhrNCSL-PbOhFTmZv29DjKnakBklu"
          
          # Check if the file was downloaded successfully
          if [ ! -f dataSetGoogle ]; then
            echo "Failed to download dataSetGoogle"
            exit 1
          fi
          
          # Execute SQL commands
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
          CREATE DATABASE IF NOT EXISTS metabase;
          ALTER USER 'metabase_user'@'%' IDENTIFIED WITH mysql_native_password BY 'securepassword';
          GRANT ALL PRIVILEGES ON metabase.* TO 'metabase_user'@'%';
          FLUSH PRIVILEGES;
          EOF
          
          # Import the SQL file
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD metabase < dataSetGoogle
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metabase-db-secret
              key: MYSQL_ROOT_PASSWORD
      restartPolicy: OnFailure
