apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql:8.4
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Install wget and gzip
          microdnf update && microdnf install -y wget gzip && microdnf clean all
          
          wget -O google-mobility.sql.gz "https://drive.google.com/uc?export=download&id=1SDsrhrNCSL-PbOhFTmZv29DjKnakBklu"
          
          if [ ! -f google-mobility.sql.gz ]; then
            echo "Failed to download google-mobility.sql.gz"
            exit 1
          fi
          
          # Decompress the file
          gunzip google-mobility.sql.gz

          if [ ! -f google-mobility.sql ]; then
            echo "Failed to decompress google-mobility.sql.gz"
            exit 1
          fi

          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
          CREATE DATABASE IF NOT EXISTS metabase;
          ALTER USER 'metabase_user'@'%' IDENTIFIED WITH mysql_native_password BY 'securepassword';
          GRANT ALL PRIVILEGES ON metabase.* TO 'metabase_user'@'%';
          FLUSH PRIVILEGES;
          EOF
          
          # Import the SQL file
          mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD metabase < google-mobility.sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: metabase-db-secret
              key: MYSQL_ROOT_PASSWORD
      restartPolicy: OnFailure
