apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      initContainers:
        - name: "sqlconnection-starter"
          image: "mysql:9.0"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: metabase-configmap
                  key: MB_DB_HOST
            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: metabase-configmap
                  key: MB_DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: DB_PASSWORD       
          command: ["sh", "-c", "mysql -h $MB_DB_HOST -P $MB_DB_PORT -u$DB_USER -p$MB_DB_PASS"] 

      containers:
        - name: metabase
          image: metabase/metabase:v0.50.20.5
          imagePullPolicy: Always
          env:
            - name: MB_DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: metabase-configmap
                  key: MB_DB_TYPE 
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: DB_NAME
            - name: MB_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: metabase-configmap
                  key: MB_DB_PORT
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: DB_USER
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: metabase-db-secret
                  key: DB_PASSWORD
            - name: MB_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: metabase-configmap
                  key: MB_DB_HOST
          ports:
            - name: metabase
              containerPort: 3000
      volumes:
        - name: secret-volume
          secret:
            secretName: metabase-db-secret
        - configMap:
            name: metabase-configmap
          name: config-volume
