apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
<<<<<<< HEAD
      storage: 100Mi
=======
      storage: 100Mi
>>>>>>> 60da909 (correcciones)
